home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from home import views

from user import views as UserViews
from reservation import views as ReservationViews


urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('hotel/', include('hotel.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),
    path('reservation/', include('reservation.urls')),
    path('admin/', admin.site.urls),

    path('login/', UserViews.login_form, name='login'),
    path('logout/', UserViews.logout_func, name='logout'),
    path('signup/', UserViews.signup_form, name='signup'),

    path('faq/', views.faq, name='faq'),
    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('references/', views.references, name='references'),
    path('contact/', views.contact, name='contact'),

    #path('roomdetail/<int:id>', views.roomdetail, name='roomdetail'),
    path('booking/', ReservationViews.booking, name='booking'),



    path('category/<int:id>/<slug:slug>', views.category_hotels, name='category_hotels'),
    path('hotel/<int:id>/<slug:slug>', views.hotel_detail, name='hotel_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addtobooking/<int:id>', views.addtobooking, name='addtobooking'),
    path('reservationroom', views.reservationroom, name='reservationroom'),
    path('deletefrombooking/<int:id>', views.deletefrombooking, name='deletefrombooking'),

]

reservation/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from hotel.models import Room

class Reservation(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False )
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class ReservationForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ['first_name','last_name','address','phone','city','country']

class ReservationRoom(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    days = models.IntegerField()
    adults = models.IntegerField()
    children = models.IntegerField()
    checkin = models.DateField(blank=True)
    checkout = models.DateField(blank=True)
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.room.title


class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    checkin = models.DateField()
    checkout = models.DateField()
    days = models.IntegerField(blank=True)
    adults = models.IntegerField()
    children = models.IntegerField()

    def __str__(self):
        return self.room.title

    @property
    def price(self):
        return (self.room.price)

    @property
    def amount(self):
        return (self.days * self.room.price)


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = ['checkout','checkin','adults','children']

reservation/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.crypto import get_random_string

from hotel.models import Room, Category
from reservation.models import Booking, BookingForm, ReservationForm, ReservationRoom, Reservation
from user.models import UserProfile


def index(request):
    return HttpResponse("reservation page")


def reservationroom(request):
    category = Category.objects.all()
    current_user = request.user
    booking = Booking.objects.filter(user_id=current_user.id)
    total = 0
    for rs in booking:
        total += rs.room.price * rs.days

    if request.method == 'POST':  # if there is a post
        form = ReservationForm(request.POST)
        # return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............

            data = Reservation()
            data.first_name = form.cleaned_data['first_name']  # get room days from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            roomcode = get_random_string(5).upper()  # random cod
            data.code = roomcode
            data.save()  #

            booking = Booking.objects.filter(user_id=current_user.id)
            for rs in booking:
                detail = ReservationRoom()
                detail.reservation_id = data.id
                detail.room_id = rs.room_id
                detail.user_id = current_user.id
                detail.days = rs.days
                detail.children = rs.children
                detail.adults = rs.adults
                detail.checkin = rs.checkin
                detail.checkout = rs.checkout
                detail.price = rs.room.price
                detail.amount = rs.amount
                detail.save()

                room = Room.objects.get(id=rs.room_id)
                room.amount -= rs.days
                room.save()

            Booking.objects.filter(user_id=current_user.id).delete()  # Clear & Delete
            request.session['booking_items'] = 0
            messages.success(request, "Your Reservation has been completed. Thank you ")
            return render(request, 'reservation_complated.html', {'roomcode': roomcode, 'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/reservation/reservationroom")

    form = ReservationForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'booking': booking,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile,
               }
    return render(request, 'reservation_form.html', context)


@login_required(login_url='/login')
def addtobooking(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information
    if request.method == 'POST':  # if there is a post
        form = BookingForm(request.POST)
        if form.is_valid():
            data = Booking()
            data.room_id = id
            data.user_id = current_user.id
            data.days = (form.cleaned_data['checkout'] - form.cleaned_data['checkin']).days
            data.checkout=form.cleaned_data['checkout']
            data.checkin=form.cleaned_data['checkin']
            data.adults = form.cleaned_data['adults']
            data.children = form.cleaned_data['children']
            data.save()  # save data
            messages.success(request, "Room successfully booked ")
            return HttpResponseRedirect("/booking")
        else:
            messages.success(request, "check error")
            return HttpResponseRedirect(url)
    else:
        return HttpResponseRedirect(url)


def booking(request):
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    booking = Booking.objects.filter(user_id=current_user.id)
    total = 0
    for rs in booking:
        total += rs.room.price * rs.days
    # return HttpResponse(str(total))
    context = {'booking': booking,
               'category': category,
               'total': total,
               }
    return render(request, 'booking_rooms.html', context)


@login_required(login_url='/login')  # Check login
def deletefrombooking(request, id):
    Booking.objects.filter(id=id).delete()
    messages.success(request, "Your Room deleted form Booking.")
    return HttpResponseRedirect("/")

reservation/templates/booking_rooms.html
{% extends 'homebase.html' %}

{% block title %}  Booking Rooms {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% load static %}
{% block body %}}
    <!-- SUB BANNER -->
    <section class="section-sub-banner bg-9">

        <div class="awe-overlay"></div>

        <div class="sub-banner">
            <div class="container">
                <div class="text text-center">
                    <h2>Booking Rooms</h2>
                </div>
            </div>

        </div>

    </section>
    <!-- END / SUB BANNER -->

    <!-- RESERVATION -->
    <section class="section-reservation-page bg-white">

        <div class="container">
            <div class="reservation-page">

                <div class="row">


                    <div class="col-md-10 col-lg-9">
                        <div class="reservation_content bg-gray">

                            <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Room</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Days</th>
                                <th class="text-center">Checkin</th>
                                <th class="text-center">Checkout</th>
                                <th class="text-center">Adults</th>
                                <th class="text-center">Children</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for rs in booking %}
                                <tr>
                                    <td class="thumb">
                                            <img src="{{ rs.room.image.url }}" alt="">
                                    </td>
                                    <td class="details">{{rs.room}}</td>
                                    <td class="price text-center"><strong>${{ rs.price }}</strong></td>
                                    <td class="qty text-center"><strong>{{rs.days}}</strong></td>
                                    <td class="date text-center"><strong>{{ rs.checkin }}</strong></td>
                                    <td class="date text-center"><strong>{{rs.checkout}}</strong></td>
                                    <td class="text text-center"><strong>{{ rs.adults }}</strong></td>
                                    <td class="text text-center"><strong>{{rs.children}}</strong></td>
                                    <td class="text-right"><a href="/reservation/deletefrombooking/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                                </tr>

                            {% endfor %}

                            </tbody>
                            <tfoot>
                                <th class="empty" colspan="3"></th>
                                <th>TOTAL</th>
                                <th colspan="2" class="total">${{ total }}</th>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <button type="submit" class="awe-btn awe-btn-13"><a href="/reservation/reservationroom"> continue to complete</a></button>
                        </div>


                        </div>

                    </div>
                </div>

            </div>
        </div>
        </div>

    </section>
    <!-- END / RESERVATION -->


{% endblock %}

reservation/templates/reservation_complated.html
{% extends 'homebase.html' %}

{% block title %}  Reservation {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% load static %}
{% block body %}}
    <!-- SUB BANNER -->
    <section class="section-sub-banner bg-9">

        <div class="awe-overlay"></div>

        <div class="sub-banner">
            <div class="container">
                <div class="text text-center">
                    <h2>RESERVATION COMPLATED</h2>
                </div>
            </div>

        </div>

    </section>
    <!-- END / SUB BANNER -->

    <!-- RESERVATION -->
    <section class="section-reservation-page bg-white">

        <div class="container">
            <div class="reservation-page">

                <div class="row">
                    <div class="col-md-12">
                        <h2>Dear {{ user.first_name }} {{ user.last_name }}</h2>
                         <br>
                        <h3>Your RESERVATION IS COMPLATED</h3>
                        <br>
                        <h3>Your code:  {{ roomcode }}</h3>
                        <br>
                        <h3>THANK YOU</h3>
                        <br>
                    </div>
                </div>

            </div>
        </div>
        </div>

    </section>
    <!-- END / RESERVATION -->


{% endblock %}

reservation/templates/reservation_form.html
{% extends 'homebase.html' %}

{% block title %}  Reservation {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% load static %}
{% block body %}}
    <!-- SUB BANNER -->
    <section class="section-sub-banner bg-9">

        <div class="awe-overlay"></div>

        <div class="sub-banner">
            <div class="container">
                <div class="text text-center">
                    <h2>RESERVATION</h2>
                </div>
            </div>

        </div>

    </section>
    <!-- END / SUB BANNER -->

    <!-- RESERVATION -->
    <section class="section-reservation-page bg-white">

        <div class="container">
            <div class="reservation-page">

                <div class="row">

                    <div class="col-md-4 col-lg-3">


                    </div>

                    <div class="col-md-8 col-lg-9">
                        <div class="reservation_content bg-gray">
                            <h2 class="reservation-heading">RESERVATION Details </h2>

                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="col-sm-6">
                                    <p><label for="id_first_name">First name:</label>
                                        <input type="text" name="first_name" value="{{ user.first_name }}" class="input"
                                               maxlength="10" required id="id_first_name"></p>
                                    <p><label for="id_last_name">Last name:</label>
                                        <input type="text" name="last_name" value="{{ user.last_name }}" class="input"
                                               maxlength="10" required id="id_last_name"></p>
                                    <p><label for="id_address">Address:</label>
                                        <input type="text" name="address" value="{{ profile.address }}" class="input"
                                               maxlength="150" id="id_address"></p>
                                    <p><label for="id_phone">Phone:</label>
                                        <input type="text" name="phone" value="{{ profile.phone }}" class="input"
                                               maxlength="20" id="id_phone"></p>
                                    <p><label for="id_city">City:</label>
                                        <input type="text" name="city" class="input" id="id_city"
                                               value="{{ profile.city }}"></p>
                                    <p><label for="id_first_name">Country :</label>
                                        <input type="text" name="country" class="input" id="id_country"
                                               value="{{ profile.country }}"></p>
                                    <div class="pull-right">
                                        <button type="submit" class="awe-btn awe-btn-13">COMPLATE RESERVATION</button>
                                    </div>

                                </div>

                                <div class="col-sm-6">
                                    <div class="section-title">
                                        <h4 class="title">Payment Information</h4>
                                    </div>
                                    <p><label for="id_first_name">Credit Card Holder</label>
                                        <input type="text" name="holder" class="input" value=""></p>
                                    <p><label for="id_first_name">Credit Card Number</label>
                                        <input type="text" name="number" class="input" value=""></p>
                                    <p><label for="id_first_name">Credit Exp Date/Year</label>
                                        <input type="text" name="ecpdate" class="input" placeholder="mm/yy"></p>
                                    <p><label for="id_first_name">Security Number</label>
                                        <input type="text" name="secnumber" class="input" value=""></p>
                                    <p><label for="id_first_name">Total: {{ total }} USD </label></p>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        </div>

    </section>
    <!-- END / RESERVATION -->


{% endblock %}